[versions]
kotlin = "2.0.0"
ktlint = "1.3.0"
spotless = "6.25.0"

[libraries]
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
